title: UISIC
description: UISIC pages

baseurl: ""

# Using a supported theme.
#theme: jekyll-theme-cayman
#theme: minima 

# Using Jekyll themes hosted on GitHub.
# For "minimal" set plugins: jekyll-remote-theme
#remote_theme: pages-themes/minimal@v0.2.0
#remote_theme: pages-themes/leap-day@v0.2.0
remote_theme: rundocs/jekyll-rtd-theme

plugins:
  - jekyll-remote-theme

# For minimal theme
#show_downloads: false

