# CI to Deploy UISIC MkDocs Pages
# From: https://squidfunk.github.io/mkdocs-material/publishing-your-site/#github-pages

name: Deploy Site

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - main
      - gh-pages
#  paths:
#      - '.github/workflows/ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      -  uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Display Python version
        run: python -c "import sys; print('Python Version=', sys.version)"

#      - name: Install dependencies           
#        - run: python -m pip install --upgrade pip
#        - run: pip install mkdocs mkdocs-material mkdocs-macros-plugin
#
#      - name: Publish docs
#        run: mkdocs gh-deploy

